# Generated by Django 3.0.6 on 2020-05-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta_det',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('total', models.FloatField(editable=False)),
                ('id_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
                ('id_producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.producto')),
            ],
        ),
    ]
